
version: '3'
services:
 server1:
   build:
     dockerfile: Dockerfile
     context: ./server
   volumes:
    - /app/node_modules
    - ./server:/app
   environment: &environment     
    - RPC_URL=http://localhost:4545